var affirmations = [
  "I can transform tragedy into comedy.",
  "With time, I have started to value more time.",
  "Some days, I can conquer the world. Other days, it takes me three hours to convince myself to shower.",
  "Hold on, I've gotta overthink about it.",
  "My alone time is sometimes for your safety.",
  "Being an adult is like folding a fitted sheet. No one really knows how.",
  "So it turns out being an adult is mostly just googling how to do stuff.",
  "I am sorry not everyone will have the pleasure of knowing me.",
  "My to-do list doesn't include dealing with negative people.",
  "I do a thing called 'what I want.",
  "It's okay if you don't like me. Not everyone has good taste.",
  "If you listen closely, you can hear me not caring.",
  "They say good things take time... that's why I'm always late.",
  "I tried to be good, then I got bored.",
  "Go to hell? Oh honey, where do you think I came from?",
  "She's beauty and she's grace, she'll punch you in the face.",
  "There is intelligent life on Earth, but I'm just visiting.",
  "I don't have a license to kill. I have a learner's permit.",
  "If you don't like my attitude, quit talking to me.",
  "Do not disturb, I'm disturbed enough already.",
  "Will smile for food.",
  "This is my cup of care. Oh look it's empty!",
  "Sorry I can't hear you over the sound of how awesome I am.",
  "No I checked my receipt, I didn't buy any of your bullshit.",
  "I used to just Crastinate. But I got so good I went Pro.",
  "Hey I found your nose. It was in my business.",
  "I'm sorry, did I roll my eyes out loud?",
  "I like my coffee how I like myself. Dark, bitter and too hot for you.",
  "Sorry if I looked interested. I'm not.",
  "Some people just need a high five. In the face. With a chair.",
  "An apple a day keeps anyone away if you throw it hard enough.",
  "Do you know what I like about people? Their dogs and cats.",
  "Before coffee: I hate everybody. After coffee: I feel good about hating everybody."
];

var mantras = [
  "Be happy. It drives people crazy.",
  "Reach for the stars, at the very least you'll air out your armpits.",
  "When something goes wrong in your life, just yell 'Plot twist!' and move on.",
  "I will drink my coffee and conquer my day.",
  "I can have peace, even when people irritate me.",
  "Sassy, Classy, and a bit smart assy.",
  "Eat, pray, slay.",
  "Sassy, Classy, and Bad-assy!",
  "I'm sexy and I know it!",
  "Be savage, not average.",
  "Twinkle twinkle I'm a star.",
  "Love is like a fart. If you have to force it, it's probably shit.",
  "Hello 911, I'm on fire.",
  "If you can't handle the sass. You can't handle this ass.",
  "Keep your head high and your middle finger higher.",
  "I'd rather be someones shot of tequila than everyones cup of tea.",
  "Out of my way I've got my sassy pants on today.",
  "Make shit happen.",
  "You are amazeballs, own that shit.",
  "Enjoy life. There's plenty of time to be dead.",
  "If nothing goes right, go left.",
  "Focused. Intelligent. Motivated. Oh, and damn sexy!",
  "Kill them with success and bury them with a smile.",
  "Why chase you when I'm the catch?",
  "Chin up or the crown slips.",
  "Throw that sass around like confetti.",
  "Keep your heels, head, and standards high.",
  "Confidence Level: Selfie with no filter.",
  "Your mind is a weapon, keep it open.",
  "Too cool to give a damn.",
  "You gotta risk it to get biscuit.",
];
